apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  annotations:
    workflows.argoproj.io/default-artifact-repository: default-v1
data:
  default-v1: |-
    archiveLogs: true
    s3:
      bucket: plrl-d-david-capi-kubeflow-pipelines
      keyPrefix: pipelines
      endpoint: s3.amazonaws.com
      region: us-east-2
      insecure: false
      keyFormat: "pipelines/{{workflow.namespace}}/pipelines/{{workflow.name}}/{{pod.name}}"
