apiVersion: v1
kind: ConfigMap
metadata:
  name: kfp-launcher
data:
  defaultPipelineRoot: {{ .Values.pipelines.storage.provider }}://{{ .Values.pipelines.storage.bucketName }}/{{ if .Values.pipelines.storage.keyPrefix }}{{ .Values.pipelines.storage.keyPrefix }}/{{ end }}{{ .Release.Namespace }}
