apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: ml-pipeline-visualizationserver
spec:
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/kubeflow/sa/{{ .Values.pipelines.apiServiceAccountName }}
  selector:
    matchLabels:
      app: ml-pipeline-visualizationserver
