apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-ui-artifact
  labels:
    app: ml-pipeline-ui-artifact
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-pipeline-ui-artifact
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ml-pipeline-ui-artifact
    spec:
      containers:
        - name: ml-pipeline-ui-artifact
          securityContext:
            {{- toYaml .Values.pipelines.deployments.uiArtifact.securityContext | nindent 12 }}
          imagePullPolicy: {{ .Values.pipelines.deployments.uiArtifact.image.pullPolicy }}
          image: "{{ .Values.pipelines.deployments.uiArtifact.image.repository }}:{{ .Values.pipelines.deployments.uiArtifact.image.tag }}"
          ports:
            - name: artifact-ui
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.pipelines.deployments.uiArtifact.resources | nindent 12 }}
      serviceAccountName: default-editor
      securityContext:
        {{- toYaml .Values.pipelines.deployments.uiArtifact.podSecurityContext | nindent 8 }}
      {{- with .Values.pipelines.deployments.uiArtifact.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pipelines.deployments.uiArtifact.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pipelines.deployments.uiArtifact.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
