apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: kubeflow-request-auth
spec:
  jwtRules:
    - fromHeaders:
      - name: cookie
        prefix: IdToken=
      issuer: https://oidc.plural.sh/
      jwksUri: https://oidc.plural.sh/.well-known/jwks.json
