apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: kubeflow-request-auth
spec:
  jwtRules:
    - forwardOriginalToken: true # Needed so that XSRF works in jupyterlab for some reason
      fromHeaders:
      - name: cookie
        prefix: IdToken=
      issuer: {{ .Values.istio.oidc.issuer }}
      jwksUri: {{ .Values.istio.oidc.jwksURI }}
