apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: kubeflow-request-auth
spec:
  jwtRules:
    - fromHeaders:
      - name: cookie
        prefix: IdToken=
      issuer: {{ .Values.istio.oidc.issuer }}
      jwksUri: {{ .Values.istio.oidc.jwksURI }}
