email: ""

serviceAccount:
  defaultEditor:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
  defaultViewer:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}

provider: ""

pipelinesBucketName: ""

aws:
  iam:
    create: false
    accountID: ""
    oidcIssuer: ""
    clusterName: ""
