nameOverride: ""
fullnameOverride: ""

email: ""

serviceAccount:
  defaultEditor:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
  defaultViewer:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}

provider: ""

pipelines:
  # enabled: true
  apiServiceAccountName: ml-pipeline

  storage:
    provider: s3
    bucketName: ""
    keyPrefix: pipelines
    endpoint: ""
    region: ""
    insecure: false

  metadata:
    grpcService:
      host: metadata-grpc-service
      port: 8080

  deployments:
    visualization:
      image:
        repository: gcr.io/ml-pipeline/visualization-server
        tag: 2.0.1
        pullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 50m
          memory: 200Mi
      securityContext: {}
      podSecurityContext: {}
      nodeSelector: {}
      tolerations: []
      affinity: {}
      serviceAccountName: default-editor
    uiArtifact:
      image:
        repository: gcr.io/ml-pipeline/frontend
        tag: 2.0.1
        pullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 100m
          memory: 500Mi
        requests:
          cpu: 10m
          memory: 70Mi
      securityContext: {}
      podSecurityContext: {}
      nodeSelector: {}
      tolerations: []
      affinity: {}
      serviceAccountName: default-editor

aws:
  region: us-east-2
  iam:
    create: false
    accountID: ""
    oidcIssuer: ""
    clusterName: ""

kubeflow:
  namespace: kubeflow

knative:
  namespace: knative

istio:
  clusterDomain: cluster.local
  ingressServiceAccount: kubeflow-gateway
  ingressNamespace: kubeflow
  oidc:
    issuer: ""
    jwksURI: ""
