nameOverride: ""
fullnameOverride: ""

email: ""

serviceAccount:
  defaultEditor:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
  defaultViewer:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}

provider: ""

pipelines:
  # enabled: true
  apiServiceAccountName: ml-pipeline

  bucketName: ""

  deployments:
    visualization:
      image:
        repository: gcr.io/ml-pipeline/visualization-server
        tag: 2.0.1
        pullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 50m
          memory: 200Mi
      securityContext: {}
      podSecurityContext: {}
      nodeSelector: {}
      tolerations: []
      affinity: {}
    uiArtifact:
      image:
        repository: gcr.io/ml-pipeline/frontend
        tag: 2.0.1
        pullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 100m
          memory: 500Mi
        requests:
          cpu: 10m
          memory: 70Mi
      securityContext: {}
      podSecurityContext: {}
      nodeSelector: {}
      tolerations: []
      affinity: {}

aws:
  iam:
    create: false
    accountID: ""
    oidcIssuer: ""
    clusterName: ""
