{{- if .Values.serviceAccount.defaultEditor.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-editor
  labels:
    {{- include "kubeflow-profile.labels" . | nindent 4 }}
  annotations:
    {{- if and .Values.aws.iam.create (eq .Values.provider "aws") }}
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.aws.iam.accountID }}:role/{{ .Values.aws.iam.clusterName }}-kubeflow-assumable-role-ns-{{ .Re.ease.Namespace }}
    {{- end }}
  {{- with .Values.serviceAccount.defaultEditor.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
