apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespaceAdmin
  annotations:
    role: admin
    user: {{ .Values.email }}
subjects:
- kind: User
  apiGroup: rbac.authorization.k8s.io
  name: {{ .Values.email }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-admin
