{{- if .Values.defaultViewer.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-viewer
  labels:
    {{- include "kubeflow-profile.labels" . | nindent 4 }}
  {{- with .Values.defaultViewer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
